/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import FightScene from "./scripts/Logic/FightScene"
import LoginPanel from "./scripts/UI/LoginPanel"
import RegistPanel from "./scripts/UI/RegistPanel"
import TextHint from "./scripts/UI/TextHint"
import LaunchGame from "./scripts/Logic/LaunchGame"
import MatchSceneUI from "./scripts/UI/MatchSceneUI"
import SpeciesChangePanel from "./scripts/UI/SpeciesChangePanel"
import MatchScene from "./scripts/UI/MatchScene"
import TestScene from "./scripts/Logic/TestScene"
import Joystick from "./scripts/Logic/Joystick"
import ChatView from "./scripts/Logic/ChatView"
import GamePanel from "./scripts/Logic/GamePanel"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("scripts/Logic/FightScene.js",FightScene);
		reg("scripts/UI/LoginPanel.js",LoginPanel);
		reg("scripts/UI/RegistPanel.js",RegistPanel);
		reg("scripts/UI/TextHint.js",TextHint);
		reg("scripts/Logic/LaunchGame.js",LaunchGame);
		reg("scripts/UI/MatchSceneUI.js",MatchSceneUI);
		reg("scripts/UI/SpeciesChangePanel.js",SpeciesChangePanel);
		reg("scripts/UI/MatchScene.js",MatchScene);
		reg("scripts/Logic/TestScene.js",TestScene);
		reg("scripts/Logic/Joystick.js",Joystick);
		reg("scripts/Logic/ChatView.js",ChatView);
		reg("scripts/Logic/GamePanel.js",GamePanel);
    }
}
GameConfig.width = 1920;
GameConfig.height = 1080;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "horizontal";
GameConfig.alignV = "middle";
GameConfig.alignH = "center";
GameConfig.startScene = "FightScene.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
